name: jasenrekisteri
version: "0"
synopsis: Member register of Satakuntalainen Osakunta
description: The software
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: satakuntalainen-osakunta/jasenrekisteri
category: Web
tested-with: GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
- base >=4.9 && <4.10
- aeson ==1.0.*
- aeson-compat
- aeson-extra
- array
- base-compat
- bytestring
- cassava
- clay
- containers
- exceptions
- file-embed
- futurice-prelude
- hashable
- http-api-data
- lens
- lucid
- mmorph
- semigroups
- servant-lucid
- strict-base-types
- swagger2
- text
- transformers
- unordered-containers
- uuid
- uuid-aeson
- vector
- vector-instances

library:
  source-dirs: src

executables:
  excel:
    main: Excel.hs
    ghc-options: -threaded
    source-dirs: excel/
    dependencies:
      - jasenrekisteri

  jasenrekisteri-server:
    main: Main.hs
    ghc-options: -threaded
    source-dirs: server/
    dependencies:
      - jasenrekisteri
      - servant        ==0.9.*
      - servant-lucid
      - servant-server ==0.9.*
      - wai
      - warp
