resolver: nightly-2018-01-09
packages:
- '.'
- location: futurice-prelude
  extra-dep: true
extra-deps:
- ansi-pretty-0.1.2.1
- fin-0
- http-types-0.11
- nf-1.0.1.0
- pretty-compact-3.0
- swagger2-2.2
