resolver: nightly-2016-10-01
packages:
- '.'
- location:
    git: https://github.com/futurice/haskell-futurice-prelude.git
    commit: b988df149f92c2ac9510bf00da8480191e326749
  extra-dep: true
- location:
    git: https://github.com/phadej/github.git
    commit: d47f3165d62feab85e85cc271d519cf87d1d3b78
  extra-dep: true
- location:
    git: https://github.com/phadej/uuid-aeson.git
    commit: 2f26dabbc8ff257d3bf49a0fafa23fc20a4f7bed
  extra-dep: true
extra-deps:
- ansi-pretty-0.1.2.0
- hsc2hs-0.68
- swagger2-2.1.3
flags: {}
extra-package-dbs: []
