resolver: nightly-2016-11-26
packages:
- '.'
- location:
    git: https://github.com/futurice/haskell-futurice-prelude.git
    commit: 65464311143537a21145877074a264aff704aa38
  extra-dep: true
- location:
    git: https://github.com/necrobious/uuid-aeson.git
    commit: f5fd573c7cb098515d0093acb2879520e190cc08
  extra-dep: true
extra-deps:
- ansi-pretty-0.1.2.0
flags: {}
extra-package-dbs: []
