flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/futurice/haskell-futurice-prelude.git
    commit: 450e61389d0d90ce98908283f929af2674bcfa1b
  extra-dep: true
- location:
    git: https://github.com/necrobious/uuid-aeson.git
    commit: f5fd573c7cb098515d0093acb2879520e190cc08
  extra-dep: true
extra-deps:
- ansi-pretty-0.1.2.0
- lens-4.15.1
resolver: nightly-2016-11-11
